stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    jobs:
      - job: terraform_plan
        displayName: Terraform Plan
        workspace:
          clean: all
        steps:
          - task: Bash@3
            displayName: terraform init
            env:
              TF_TOKEN_app_terraform_io: $(tfc_token)
              TF_WORKSPACE: $(workspace)-$(environment)
            inputs:
              targetType: filePath
              filePath: scripts/terraform_init.sh
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform

          - task: Bash@3
            displayName: terraform plan
            name: plan # needed for result later
            env:
#              TF_TOKEN_app_terraform_io: $(tfc_token)
              TF_WORKSPACE: $(workspace)-$(environment)
              TF_VAR_env: $(environment)
            inputs:
              targetType: filePath
              filePath: scripts/terraform_plan.sh
              workingDirectory: $(System.DefaultWorkingDirectory)/terraform
              arguments: >
                -out tfplan.tfout

          - task: CopyFiles@2
            displayName: stage files to $(Build.StagingDirectory)
            condition: and(succeeded(), eq(variables['plan.result'], 'changed'))
            inputs:
              sourceFolder: $(System.DefaultWorkingDirectory)
              contents: |
                terraform/**/*
                modules/**/*
                !scripts/**/*
                !pipelines/**/*
                !.gitignore
                !**/.git/**/*
                !terraform/.terraform/**/*
              targetFolder: $(Build.StagingDirectory)
              cleanTargetFolder: true

          - task: PublishBuildArtifacts@1
            displayName: upload tf artifact
            condition: and(succeeded(), eq(variables['plan.result'], 'changed'))
            inputs:
              artifactName: terraform-plan